# Generated by Django 5.2.4 on 2025-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_completo', models.CharField(max_length=90, verbose_name='Nombre')),
                ('Email_corporativo', models.EmailField(max_length=254)),
                ('Teléfono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('Cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('Departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('Fecha_de_contratación', models.DateTimeField(auto_now_add=True)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
