# Generated by Django 5.1.5 on 2025-07-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0002_departamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Administradores',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
    ]
